name: Bug report
description: File a bug report
labels: [bug, pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file this bug report.
  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      placeholder: |
        <!--
          What did you do? (Provide reproduction code in next section)

          What did you expect to happen?

          What happened instead?

          Do you have an error stack-trace?
        -->
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: |
        A minimal reproduction is necessary so others can understand and debug your bug.

        Provide a link to a minimal reproduction repository:
        - Set the command to run in the `package.json` script `start`
        - For a starter template, [fork this template on StackBlitz](https://stackblitz.com/edit/node-guv65j?file=webpack.config.js&view=editor)
        - No more than 10 files. Delete irrelevant files (e.g. `LICENSE`, `.npmrc`, `.github`). This is the first step of debugging so doing this will save us work.
          👉 **Tip:** The _smaller_ the reproduction, the _faster_ we can debug and resolve your issue

        ⚠️ If a _minimal_ reproduction is not provided, the issue will be closed
      placeholder: 👆 Your issue will be CLOSED if it doesn't follow the instructions above.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Node.js package manager
      description: Which package manager are you using? [npm](https://docs.npmjs.com/cli/v7/commands/npm), [yarn](https://yarnpkg.com/), or [pnpm](https://pnpm.io/)
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Run and paste the output of:
        ```
        npx envinfo --system --npmPackages webpack,esbuild-loader --binaries
        ```
        
        This information is used to for reproduction and debugging.
      placeholder: |
        System:
          OS:
          CPU:
          Shell:
        Binaries:
          Node:
          npm:
        npmPackages:
          webpack:
          esbuild-loader:
      render: shell
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Can you contribute a fix?
      description: We would love it if you can open a pull request to fix this bug!
      options:
        - label: I’m interested in opening a pull request for this issue.
