blank_issues_enabled: false
contact_links:
  - name: Help / Questions / Discussions
    url: https://github.com/esbuild-kit/esbuild-loader/discussions
    about: Use GitHub Discussions for anything else

  - name: Priority support ⭐️
    url: https://github.com/sponsors/privatenumber/
    about: Join our community of sponsors and enjoy priority attention for all your questions and concerns
